### ISSUE TITLE
Update to AR Foundation 3.0

### ISSUE THREAD

**Issue by neogeek** [CandyCoded/ARFoundation-Components#8]

**Comment by FaberVi** [comment]
You can update it for new preview? You should also update the instructions for compiling on Android. Multithreading check now works and is now supported

**Comment by neogeek** [comment]
@D3m0n92 Thanks for the info regarding the Multithreading! I've updated the README to reflect that update.

This is unfortunately blocked due to an issue regarding shaders and MacOS Catalina <https://forum.unity.com/threads/installing-unity-on-macos-catalina.689089/>. I'll keep an eye on that forum post, but I assume I will have to wait until 2019.3 comes out of beta before I can release an update.

**Comment by neogeek** [comment]
I've updated the AR Foundation plugins, now that Unity 2019.3 has been released, and things seem to work again!

https://github.com/CandyCoded/ARFoundation-Components/releases/tag/v3.1.0

🎉
